### ISSUE TITLE
Set Hide "Tab Bar" as default

### ISSUE THREAD

**Issue by TiWe1998** [amitdar/FullPageDashboard#6]
Hello. 

When the Raspberry restarts, the pin settings are back to default and the tab bar is displayed. 

Can you set the whole thing so that the tab bar is automatically hidden even when the Raspberry restarts? That this setting is saved?

Best
Tim

**Comment by guysoft** [comment]
Just to note that @amitdar can. The question is does he have the time? :)

**Comment by amitdar** [comment]
Hi @TiWe1998,
I've just fixed the issue. (https://github.com/amitdar/FullPageDashboard/commit/c4e02a70e47d9842d5c13cd9eefbc9abf8a9b607)

Amit
