### ISSUE TITLE
Cycle through URLs based on time of day instead of a timer

### ISSUE THREAD

**Issue by bradlet21** [amitdar/FullPageDashboard#7]
Hi, I use FullPageOS to display some internally hosted websites. I would like to display 1 website between certain hours of the day, and then switch to a second website in the evening. Would it be possible to add that functionality instead of the timer?

**Comment by guysoft** [comment]
I am afraid @amitdar isn't actively maintaining this anymore. If you want more features you would have to write them / hire someone to write them yourself.

**Comment by bradlet21** [comment]
@guysoft all good, I appreciate you taking the time to let me know!
